const helpers={
// login
FETCH_LOGIN:"FETCH_LOGIN",
FETCH_LOGIN_SUCCESS:"FETCH_LOGIN_SUCCESS",
FETCH_LOGIN_ERROR:"FETCH_LOGIN_ERROR",

// signup
FETCH_SIGNUP:"FETCH_SIGNUP",
FETCH_SIGNUP_SUCCESS:"FETCH_SIGNUP_SUCCESS",
FETCH_SIGNUP_ERROR:"FETCH_SIGNUP_ERROR",

// list products
FETCH_PRODUCTS:"FETCH_PRODUCTS",
FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
FETCH_PRODUCTS_ERROR:"FETCH_PRODUCTS_ERROR",

// add products
FETCH_ADD_PRODUCT:"FETCH_ADD_PRODUCT",
FETCH_ADD_PRODUCT_SUCCESS:"FETCH_ADD_PRODUCT_SUCCESS",
FETCH_ADD_PRODUCT_ERROR:"FETCH_ADD_PRODUCT_ERROR",
}

export default helpers;